{{- if .Values.gtp5gOperator.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gtp5gmodules.operator.gthulhu.io
spec:
  group: operator.gthulhu.io
  names:
    kind: GTP5GModule
    listKind: GTP5GModuleList
    plural: gtp5gmodules
    singular: gtp5gmodule
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              version:
                pattern: ^v[0-9]+\.[0-9]+\.[0-9]+$
                type: string
              kernelVersion:
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                type: object
              image:
                type: string
            required:
            - version
            type: object
          status:
            properties:
              phase:
                enum:
                - Pending
                - Installing
                - Installed
                - Failed
                type: string
              installedNodes:
                items:
                  type: string
                type: array
              message:
                type: string
              lastUpdateTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
{{- end }}
