{{/*
  mTLS Secret — raw PEM files consumed by Manager and DM sidecar via env vars.
  Created only when mtls.enabled=true and no existingSecret is provided.
*/}}
{{- if and .Values.mtls.enabled (not .Values.mtls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gthulhu.fullname" . }}-mtls-certs
  labels:
    {{- include "gthulhu.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.mtls.ca.cert | nindent 4 }}
  dm.crt: |
    {{- .Values.mtls.dm.cert | nindent 4 }}
  dm.key: |
    {{- .Values.mtls.dm.key | nindent 4 }}
  manager.crt: |
    {{- .Values.mtls.manager.cert | nindent 4 }}
  manager.key: |
    {{- .Values.mtls.manager.key | nindent 4 }}
{{- end }}
---
{{/*
  Scheduler mTLS config overlay — a Secret that contains the full scheduler
  config.yaml with PEM material inlined.  Mounted via projected volume so it
  overrides the ConfigMap's config.yaml while keeping jwt_public_key.pem from
  the ConfigMap.
*/}}
{{- if and .Values.scheduler.enabled .Values.mtls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gthulhu.fullname" . }}-scheduler-mtls-config
  labels:
    {{- include "gthulhu.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
type: Opaque
immutable: true
stringData:
  config.yaml: |
    # Gthulhu Scheduler Configuration (mTLS enabled)
    scheduler:
      slice_ns_default: 20000000
      slice_ns_min: 1000000
      mode: gthulhu
      kernel_mode: true
      max_time_watchdog: true
    api:
      enabled: true
      auth_enabled: true
      url: https://localhost:{{ .Values.scheduler.sidecar.port }}
      interval: 5
      public_key_path: /etc/gthulhu/jwt_public_key.pem
      mtls:
        enable: true
        cert_pem: |
          {{- .Values.mtls.manager.cert | nindent 10 }}
        key_pem: |
          {{- .Values.mtls.manager.key | nindent 10 }}
        ca_pem: |
          {{- .Values.mtls.ca.cert | nindent 10 }}
    debug: false
    early_processing: false
    builtin_idle: false
{{- end }}
