{{- if and .Values.service.enabled .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gthulhu.fullname" . }}-api
  labels:
    {{- include "gthulhu.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gthulhu.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
